### ISSUE TITLE
POM missing 

### ISSUE THREAD

**Issue by passion4code** [spring-projects/spring-test-mvc#71]
Greetings.

Sorry to be a bother. But I've noticed that our nexus is able to pull down the maven-metadata.xml when pulling down your awesome dependency, but stops on the POM file. 

[WARNING] The POM for org.springframework:spring-test-mvc:jar:1.0.0.BUILD-SNAPSHOT is missing, no dependency information available.

Did you want snippets of my pom.xml?

**Comment by apennebaker-ni** [comment]
Please publish 1.0.0.M2 to the central Maven repo again, complete with the pom file. Some of us still use this!

**Comment by snicoll** [comment]
Hello, milestone releases are not published to Maven central. You should use the [milestone repository](http://repo.spring.io/milestone/) for such artifact.

That artifact is here: http://repo.spring.io/milestone/org/springframework/spring-test-mvc/1.0.0.M2/

**Comment by rstoyanchev** [comment]
@apennebaker-ni, you are on Spring Framework 3.1.x I presume? If not please switch to the spring-test module. Spring Framework 3.1.x is no longer in active development.
