### ISSUE TITLE
MockRestServiceServer doesn't inherit timeout and retry settings for RestTemplate

### ISSUE THREAD

**Issue by NZhuravlev** [spring-projects/spring-test-mvc#89]
Since MockRestServiceServer simply replaces RestTemplate requestFactory and requestFactory serves as the holder of HttpClient and timeouts settings you will get irrelevant test results in case you'll make your own realisation of ResponseCreator with timeout simulation.

**Comment by rstoyanchev** [comment]
@NZhuravlev, see the note in the README. This repository is no longer where the source is maintained. In fact at this point we should just remove it. 

I presume you're not using Spring Framework 3.1 so please create a ticket in the Spring Framework JIRA https://jira.spring.io/browse/SPR.
